{% set name = "knack" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7fcab17585c0236885eaef311c01a1e626d84c982aabcac81703afda3f89c81f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - argcomplete
    - jmespath
    - pygments
    - pyyaml
    - tabulate

test:
  imports:
    - knack
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/knack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Command-Line Interface framework

  doc_url: https://github.com/Microsoft/knack/tree/master/docs
  dev_url: https://github.com/microsoft/knack

extra:
  recipe-maintainers:
    - awvwgk
    - dhirschfeld
    - andreyz4k
